# Generated by Django 3.2.19 on 2023-06-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20230617_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password1',
            field=models.CharField(default='password', max_length=20),
        ),
    ]
