# Generated by Django 3.2.19 on 2023-06-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
